/** @type {import('tailwindcss').Config} */
export default {
        darkMode: "class",
        content: [
                "./index.html",
                "./src/**/*.{js,ts,jsx,tsx}",
        ],
        theme: {
                extend: {
                        "colors": {
                                "on-secondary": "#283501",
                                "secondary-container": "#3e4c16",
                                "on-primary-fixed-variant": "#6b3743",
                                "surface": "#111317",
                                "secondary": "#bdce89",
                                "on-primary": "#50212d",
                                "on-error": "#690005",
                                "surface-container-high": "#282a2e",
                                "on-error-container": "#ffdad6",
                                "on-tertiary": "#4d2600",
                                "on-secondary-container": "#acbc7a",
                                "inverse-on-surface": "#2f3035",
                                "outline": "#9e8c8f",
                                "on-primary-container": "#7b4551",
                                "on-surface": "#e2e2e8",
                                "on-background": "#e2e2e8",
                                "on-secondary-fixed": "#161f00",
                                "surface-container-highest": "#333539",
                                "tertiary-fixed-dim": "#ffb77d",
                                "inverse-surface": "#e2e2e8",
                                "on-tertiary-fixed": "#2f1500",
                                "primary-fixed": "#ffd9df",
                                "surface-tint": "#fbb3c1",
                                "on-tertiary-fixed-variant": "#6e3900",
                                "outline-variant": "#514345",
                                "primary-fixed-dim": "#fbb3c1",
                                "on-surface-variant": "#d6c2c4",
                                "tertiary-fixed": "#ffdcc3",
                                "primary": "#ffdee3",
                                "surface-dim": "#111317",
                                "secondary-fixed": "#d9eaa3",
                                "surface-bright": "#37393e",
                                "inverse-primary": "#864e5a",
                                "primary-container": "#ffb7c5",
                                "surface-variant": "#333539",
                                "tertiary": "#ffe0cb",
                                "error-container": "#93000a",
                                "secondary-fixed-dim": "#bdce89",
                                "tertiary-container": "#ffbc87",
                                "surface-container-lowest": "#0c0e12",
                                "on-tertiary-container": "#824500",
                                "on-secondary-fixed-variant": "#3e4c16",
                                "surface-container-low": "#1a1c20",
                                "on-primary-fixed": "#360c19",
                                "error": "#ffb4ab",
                                "background": "#111317",
                                "surface-container": "#1e2024"
                        },
                        "borderRadius": {
                                "DEFAULT": "0.125rem",
                                "lg": "0.25rem",
                                "xl": "0.5rem",
                                "full": "0.75rem"
                        },
                        "spacing": {
                                "margin-mobile": "24px",
                                "section-gap": "80px",
                                "container-max": "1440px",
                                "margin-desktop": "80px",
                                "gutter": "32px",
                                "unit": "8px"
                        },
                        "fontFamily": {
                                "body-md": ["'Zen Kaku Gothic New'", "sans-serif"],
                                "headline-lg-mobile": ["EB Garamond"],
                                "headline-lg": ["EB Garamond"],
                                "label-sm": ["'Zen Kaku Gothic New'", "sans-serif"],
                                "headline-md": ["EB Garamond"],
                                "body-lg": ["'Zen Kaku Gothic New'", "sans-serif"],
                                "display-lg": ["EB Garamond"]
                        },
                        "fontSize": {
                                "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
                                "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "500" }],
                                "headline-lg": ["48px", { "lineHeight": "1.2", "fontWeight": "500" }],
                                "label-sm": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "600" }],
                                "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "400" }],
                                "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0.01em", "fontWeight": "400" }],
                                "display-lg": ["80px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "500" }]
                        }
                },
        },
        plugins: [],
}
